export const BUTTON_CLICK_ACTION = 'BUTTON_CLICK_ACTION'
export const DECREMENT = 'DECREMENT'
export const INCREMENT = 'INCREMENT'
export const CHANNEL_DETAIL = 'CHANNEL_DETAIL'
export const SET_COLLAPSED = 'SET_COLLAPSED'
export const SET_HEADER_LIST = 'SET_HEADER_LIST'

